version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: weekly
    groups:
      npm dev minor:
        dependency-type: development
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: ci
